CREATE TABLE IF NOT EXISTS USER_INFO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	FULL_NAME VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR (255) NOT NULL,
	EMAIL VARCHAR (255) NOT NULL,
	PHONE_NUMBER VARCHAR (255) NOT NULL,
	ROLE VARCHAR (255) NOT NULL,
	POINT INT NOT NULL DEFAULT 0,
	IS_ACTIVE BOOLEAN
);

INSERT INTO USER_INFO (FULL_NAME, USERNAME, PASSWORD, EMAIL, PHONE_NUMBER, `ROLE`, POINT, IS_ACTIVE)
VALUES('Quan Pham', 'quanpv', '492ea1da80b3844453ac7a5fba634991', 'phamquan1105@gmail.com', '0979508629', 'ADMIN', 0, 1);

INSERT INTO USER_INFO(FULL_NAME, USERNAME, PASSWORD, EMAIL, PHONE_NUMBER, `ROLE`, POINT, IS_ACTIVE)
VALUES('Lam Vu', 'lamvv', '492ea1da80b3844453ac7a5fba634991', 'lamvv@gmail.com', '0979508629', 'BASIC', 100, 1);


CREATE TABLE IF NOT EXISTS USER_SHOP (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	SHOP_ID VARCHAR(255) NOT NULL,
	IS_ACTIVE BOOLEAN
);

INSERT INTO USER_SHOP(USER_ID, SHOP_ID, IS_ACTIVE) VALUES(1, 'vidachatluongcao', 1);

CREATE TABLE IF NOT EXISTS FOLLOW (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SHOP_ID INT NOT NULL,
	FOLLOWER INT NOT NULL
);

